### ISSUE TITLE
Cannot build executable Jar

### ISSUE THREAD

**Issue by realulim** [UniconLabs/bootiful-cas-client#3]
The application runs fine with bootRun, however, if a Jar is built via bootJar and then started via java -jar bootiful-cas-client.jar, the Thymeleaf templates are not found. This message appears in the log, when the start page is called:

org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/fragments/layout", template might not exist or might not be accessible by any of the configured Template Resolvers (template: "index" - line 4, col 7)

I believe this has to do with the fact that bootRun is smarter than bootJar and can fix a couple of errors / omissions by itself. I believe the templates are either in the wrong part of the jar or there is some configuration missing.

**Comment by realulim** [comment]
This fixes the problem (in Java):

```
@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Bean
    @Description("Thymeleaf template resolver serving HTML 5")
    public ClassLoaderTemplateResolver templateResolver() {

        ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();

        templateResolver.setPrefix("templates/");
        templateResolver.setCacheable(false);
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode("HTML5");
        templateResolver.setCharacterEncoding("UTF-8");

        return templateResolver;
    }
}
```
The important part is setting the prefix.

**Comment by dima767** [comment]
Thanks for reporting it!

**Comment by dima767** [comment]
This has been fixed
